"""add user model preference

Revision ID: b8f3b190ffa4
Revises: 6e8e4bcb1a32
Create Date: 2026-05-21 00:11:57.689281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8f3b190ffa4'
down_revision: Union[str, None] = '6e8e4bcb1a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usermodelpreference_model_id_fkey'), 'usermodelpreference', type_='foreignkey')
    op.create_foreign_key(None, 'usermodelpreference', 'trainingrun', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usermodelpreference', type_='foreignkey')
    op.create_foreign_key(op.f('usermodelpreference_model_id_fkey'), 'usermodelpreference', 'modelartifact', ['model_id'], ['id'])
    # ### end Alembic commands ###

